export {default as MainPage} from './main-page/main-page'
export {default as TeamPage} from './team-page/team-page'
export {default as Price} from './price-page/price-page'
export {default as Contacts} from './contacts-page/contacts-page'
export {default as NotFoundPage} from './not-found/not-found'